title: "Functional Meta-Omics: Bioinformatics in Action"
description: "Hands-on workshop on functional meta-omics."
theme: jekyll-theme-cayman
plugins:
  - jekyll-octicons

markdown: kramdown
kramdown:
  parse_block_html: true
