title: "Functional Meta-Omics: Bioinformatics in Action"
description: "This hands-on workshop introduces participants to the bioinformatics of functional meta-omics, combining metagenomics and metaproteomics to explore microbial communities from genes to functions. "
theme: jekyll-theme-cayman
plugins:
  - jekyll-octicons






